name: DevOps Integração Contínua
# Definir os gatilhos para o workflow
on:
  push:
    branches:
      - main  # Ou qualquer outra branch que deseja monitorar

# Configuração das jobs do workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Executa em uma máquina Ubuntu

    steps:
    # 1. Checar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar Node.js (Exemplo de aplicação Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Ou qualquer versão necessária para o seu app

    # 3. Instalar dependências
    - name: Install dependencies
      run: npm ci

    # 4. Rodar os testes (Opcional, pode ser removido se não for necessário)
    # - name: Run tests
    #  run: npm run test


    - name: Show current working directory
      run: pwd

    - name: List files in repository root after checkout
      run: ls -la

    - name: List files inside the 'server' folder (if it exists)
      # Tente listar o conteúdo da sua pasta 'server'.
      # Se esta etapa falhar, a pasta 'server' realmente não foi encontrada no local esperado.
      run: ls -la ./server/


    # 5. Iniciar o servidor
    - name: Start the server
      working-directory: ./server
      run: node server.js

    # 6. Iniciar a aplicação
    - name: Start the application
      run: npm run start

